### ISSUE TITLE
Memory leaks reported by Unity

### ISSUE THREAD

**Issue by martinkallstrom** [tyoden/VoronoiUnityBurst#1]
Hi, I spent a couple of hours yesterday fixing a bunch of memory leaks that were reported by Unity when I was running the demo project. Are you interested in seeing the fixes? Maybe it was something that was only appearing on my setup (old dual-core Mac).

**Comment by grimseal** [comment]
Hi. Yes, you are free to make a pull request. 
I know that in one case there is a memory leak. Because I do not release the allocated memory if the union of Voronoi diagrams throws an exception. I am currently trying to fix merge errors that result from rounding floating point numbers for this algorithm http://www.personal.kent.edu/~rmuhamma/Compgeometry/MyCG/Voronoi/DivConqVor/divConqVor.htm.
